import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import {Fragment} from 'react';
import About from '~/components/About';
import Contact from '~/components/Contact';
import Header from '~/components/Header';
import Nav from '~/components/Nav';
import Experience from '~/components/Experience';
import Services from '~/components/Services';

export default function Home() {
	return (
		<Fragment>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.container}>
				<Header />
				<About />
				<Experience />
				<Services />
				<Contact />
				<Nav />
			</div>
		</Fragment>
	);
}
